workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "ru.assistant.ai"
    scripts:
      - name: Build Android
        script: |
          cd app
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
